#!/bin/bash -l
#BSUB -P stf218
#BSUB -J restart
#BSUB -o logs.o%J
#BSUB -W 0:10
#BSUB -nnodes 1
#BSUB -alloc_flags "smt4 nvme"
##BSUB -q debug


model_size=$1 
module load gcc/9.1.0
module unload darshan-runtime

echo $model_size


NODES=$(cat ${LSB_DJOB_HOSTFILE} | sort | uniq | grep -v login | grep -v batch | wc -l)

#head=$(cat ${LSB_DJOB_HOSTFILE} | sort | uniq | grep -v login | grep -v batch | head -n1)

#ssh $head nvidia-smi stats -d gpuUtil,memUtil -f $(pwd)/log.gpu.n${NODES}.${LSB_JOBID} &

jsrun -n${NODES} -a 6 -c 42  -g 6 -r 1 --bind=proportional-packed:7 --launch_distribution=packed ./hea-wl ptrun3D.input 123

#jskill all
