#!/bin/bash
# Begin LSF directives
#BSUB -P stf011
#BSUB -J deepbench
#BSUB -o tst.o%J
#BSUB -W 00:30
#BSUB -nnodes 1
# End LSF directives and begin shell commands

# env
module load cuda

BENCH_ROOT=./src/bin
CONV_BENCH=$BENCH_ROOT/conv_bench

# build 
if [ ! -f  $CONV_BENCH ]; then
    pushd ./src
    make USE_TENSOR_CORES=0
    popd
fi

jsrun -n1 -a1 -c42 -g1 -r1 --smpiargs="-disable_gpu_hooks" -b rs ${CONV_BENCH} float > log.fp32 



