#!/bin/bash -l
#BSUB -P stf218
#BSUB -J restart
#BSUB -o logs.o%J
#BSUB -W 0:30
#BSUB -nnodes 64
#BSUB -alloc_flags "smt4 nvme"
#BSUB -q debug


source env.sh

export SMARTSIM_LOG_LEVEL=developer
export OMP_NUM_THREADS=4

NODES=$(cat ${LSB_DJOB_HOSTFILE} | sort | uniq | grep -v login | grep -v batch | wc -l)
for g in $(seq 1 6); do
    jsrun -n${NODES} -a1 -c2 -g1 -r1 redis-server --port $((6780+g)) --logfile /tmp/log.$g  --loadmodule ${REDIS_DIR}/lib/redisai.so &
done
sleep 10

export PAMI_IBV_ENABLE_DCT=0
export PAMI_ENABLE_STRIPING=0
export PAMI_IBV_ADAPTER_AFFINITY=1
export PAMI_IBV_DEVICE_NAME="mlx5_0:1"
export PAMI_IBV_DEVICE_NAME_1="mlx5_3:1"

ENABLE_SHARP="-E HCOLL_MAIN_IB=mlx5_0:1 -E HCOLL_ENABLE_SHARP=2 -E HCOLL_SHARP_NP=2 -E SHARP_COLL_LOG_LEVEL=3 -E HCOLL_BCOL_P2P_ALLREDUCE_SHARP_MAX=2048 -E SHARP_COLL_JOB_QUOTA_OSTS=64 -E SHARP_COLL_POLL_BATCH=1 -E SHARP_COLL_SHARP_ENABLE_MCAST_TARGET=0 -E SHARP_COLL_ENABLE_MCAST_TARGET=0 -E SHARP_COLL_JOB_QUOTA_PAYLOAD_PER_OST=256"

ENABLE_HCOLL="-mca coll_hcoll_enable 1 -mca coll_hcoll_np 0 -mca coll ^basic -mca coll ^ibm -HCOLL -FCA"


if (( NODES > 256 ))
then 
    jsrun -n${NODES} -a 6 -c 30 -r 1 --bind=proportional-packed:2 --launch_distribution=packed $ENABLE_SHARP --smpiargs="$ENABLE_HCOLL" ./hea-wl wlrun1D.input 123
else
    jsrun -n${NODES} -a 12 -c 24 -r 1 --bind=proportional-packed:2 --launch_distribution=packed ./hea-wl wlrun1D.input 123
fi
