CC = mpic++
TF_DIR = /sw/summit/open-ce/anaconda-base/envs/open-ce-1.4.0-py39-0
Flag = -O2 -g -Wno-narrowing -rdynamic -isystem ${TF_DIR}/lib/python3.9/site-packages/tensorflow/include  -isystem /gpfs/alpine/scratch/junqi/stf218/mcml/SmartRedis/install/include  -D_GLIBCXX_USE_CXX11_ABI=1   -std=c++17
LDFlag =  -g -D_GLIBCXX_USE_CXX11_ABI=1 -rdynamic  -Wl,-rpath,${TF_DIR}/lib/python3.9/site-packages/tensorflow -Wl,--allow-multiple-definition -Wl,--whole-archive ${TF_DIR}/lib/python3.9/site-packages/tensorflow/libtensorflow_cc.so -Wl,--no-whole-archive ${TF_DIR}/lib/python3.9/site-packages/tensorflow/libtensorflow_framework.so  -Wl,-rpath,/gpfs/alpine/scratch/junqi/stf218/mcml/SmartRedis/install/lib -L/gpfs/alpine/scratch/junqi/stf218/mcml/SmartRedis/install/lib  -lsmartredis
WL_Flag ?= -DGLOBAL_UPDATE
Backend_Flag ?=

relax_dir = relax
hist_dir = hist
objs = \
	rand.o parameter.o allreduce.o\
	alloy.o wanglandau.o pt.o \
	main.o 

relax_objs = $(addprefix $(relax_dir)/, $(objs))
hist_objs = $(addprefix $(hist_dir)/, $(objs))

Exe = hea-wl
Objects = $(objs) $(relax_objs) $(hist_objs)
tmpdir = $(relax_dir) $(hist_dir)
all: $(Exe)
$(relax_dir):
	mkdir -p $(relax_dir)
$(hist_dir):
	mkdir -p $(hist_dir)
hea-wl: $(objs) 
	$(CC) $(objs) $(LDFlag) -o $@
hea-wl-relax: $(relax_objs)
	$(CC) $(relax_objs) $(LDFlag) -o $@
hea-wl-hist: $(hist_objs)
	$(CC) $(hist_objs) $(LDFlag) -o $@
$(relax_objs): Flag+=-DTime_Series 
$(hist_objs): Flag+=-DHIST
%.o: %.cc
	$(CC) -c $(Flag) $(Backend_Flag) ${WL_Flag} $< -o $@
$(relax_dir)/%.o: %.cc
	$(CC) -c $(Flag) $(Backend_Flag) ${WL_Flag} $< -o $@
$(hist_dir)/%.o: %.cc
	$(CC) -c $(Flag) $(Backend_Flag) ${WL_Flag} $< -o $@
clean:
	rm -rf $(Exe) $(Objects) $(tmpdir)
